// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package persons

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PersonsClient is the client API for Persons service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PersonsClient interface {
	Person(ctx context.Context, in *TestRequest, opts ...grpc.CallOption) (*TestResponse, error)
}

type personsClient struct {
	cc grpc.ClientConnInterface
}

func NewPersonsClient(cc grpc.ClientConnInterface) PersonsClient {
	return &personsClient{cc}
}

func (c *personsClient) Person(ctx context.Context, in *TestRequest, opts ...grpc.CallOption) (*TestResponse, error) {
	out := new(TestResponse)
	err := c.cc.Invoke(ctx, "/backend.Persons/Person", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PersonsServer is the server API for Persons service.
// All implementations must embed UnimplementedPersonsServer
// for forward compatibility
type PersonsServer interface {
	Person(context.Context, *TestRequest) (*TestResponse, error)
	mustEmbedUnimplementedPersonsServer()
}

// UnimplementedPersonsServer must be embedded to have forward compatible implementations.
type UnimplementedPersonsServer struct {
}

func (UnimplementedPersonsServer) Person(context.Context, *TestRequest) (*TestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Person not implemented")
}
func (UnimplementedPersonsServer) mustEmbedUnimplementedPersonsServer() {}

// UnsafePersonsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PersonsServer will
// result in compilation errors.
type UnsafePersonsServer interface {
	mustEmbedUnimplementedPersonsServer()
}

func RegisterPersonsServer(s grpc.ServiceRegistrar, srv PersonsServer) {
	s.RegisterService(&Persons_ServiceDesc, srv)
}

func _Persons_Person_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonsServer).Person(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backend.Persons/Person",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonsServer).Person(ctx, req.(*TestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Persons_ServiceDesc is the grpc.ServiceDesc for Persons service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Persons_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "backend.Persons",
	HandlerType: (*PersonsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Person",
			Handler:    _Persons_Person_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "persons.proto",
}
