version: "3"

services:
  atm_frontend: &app
    tty: true
    build:
      context: ./frontend
      dockerfile: ../compose/DockerfileFrontEnd
      args:
        - VUE_APP_API_URL=http://backend:11080
    container_name: atm_frontend
    hostname: atm_frontend
    ports:
      - "2015:2015"
    expose:
      - "2015"
    volumes:
      - ./frontend:/app:delegated
    depends_on:
      - atm_backend
    environment:
      - VUE_APP_API_URL=http://backend:11080
    command: npm run serve -- --port 2015


  atm_backend:
    tty: true
    build:
      context: ./backend
      dockerfile: ../compose/DockerfileBackEnd
    container_name: atm_backend
    hostname: atm_backend
    ports:
      - "17000:17000"
    expose:
      - "11080"
    depends_on:
      - atm_db
    environment:
      - DATABASE_URL=postgres://admin:password@db:5432/todos?sslmode=disable

  atm_db:
    image: postgres
    container_name: atm_db
    hostname: atm_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=todos
#
#  atm_tests:
#    tty: true
#    build:
#      context: ./tests
#      dockerfile: ../compose/DockerfileCypress
#    container_name: atm_tests
#    depends_on:
#      - atm_frontend
#      - atm_backend
#      - atm_db
#    environment:
#      - DATABASE_URL=postgres://admin:password@db:5432/todos?sslmode=disable
#      - CYPRESS_FRONTEND_URL=http://frontend:2015
#    volumes:
#      - "./tests/cypress:/home/node/tests/cypress"
#      - "./tests/report:/home/node/tests/report"
